/**
* @author Alexander Davydov
* @description 
*/
public class Class13
{
/**
* @description 
*/
integer a = 132;

				   /**
				   * @description 
				   * @param integerParam 
				   * @param stringParam 
				   * @param classNewParam 
				   * @return List<integer> 
				   */
			public static List<integer> method(
			List<integer> integerParam,
			List<List<string>> stringParam,
			List<List<List<Class_new>>> classNewParam)
			{
			return new List<integer>(1);
			}
/**
* @description 
* @param class2Var 
* @param class3Var 
*/
private virtual void method1(class2 class2Var, Class3 class3Var){}
/**
* @description 
*/
integer ab = 2;
}