virtual public class Class100
{
	public Class100()
	{
	}

	public class ClassNewInside
	{
		public ClassNewInside()
		{
		}

		public void ClassNewInsideMethod()
		{
		Integer totalAmount = 5;
			if (totalAmount > = 0) 
			 {
			 }
		}

		/*
		//not supported by Apex language
		
		public class ClassNewInside1
		{
			public ClassNewInside1()
			{
			}

			public void Hello1()
			{
			}
		}*/
		



		public void Hello()
		{
		}
	}


	public void Hello123()
	{
	        //
			//TMS_Webservices_Utility.CheckDealerCode('test');
            //TMS_Webservices_Utility.CheckDealerCode(null);
			//TMS_Webservices_Utility res = new TMS_Webservices_Utility();


		ClassNewInside class111 = new ClassNewInside();
		class111.ClassNewInsideMethod();
	}
}